### ISSUE TITLE
Discovery file extension support in Workbench CAD Reader Route

### ISSUE THREAD

**Issue by Bharat1594** [pyansys/pyprimemesh#276]
Hi Team,

We tried to read .dsco file through the Workbench CAD reader route.

mesher.read(os.path.join(wkdir,r"Pipe.dsco"),cad_reader_route=prime.CadReaderRoute.WORKBENCH)

After running the code, I am getting error "CAD Import Failure". After I tried with installing CAD Configuration as well. Once CAD Configuration was done, I still got the same issue.
![CAD_Import_Failure](https://user-images.githubusercontent.com/81905655/207232304-04dbafca-30fc-4785-8f55-d48652c11f2b.jpg)

**Comment by waltersma** [comment]
@Bharat1594 , @hlee0122 , @rajesh1359 update on this issue is fix should be available in 0.4.0.Dev3.
