### ISSUE TITLE
JT import fails to load volume zones

### ISSUE THREAD

**Issue by Rohits28** [pyansys/pyprimemesh#286]
Hi,

I am following a documentation for Reading and writing files which says Body names should assign to volume zones while importing file in pyprime. (https://dev.prime.docs.pyansys.com/user_guide/fileio.html#part-management-and-creation)
I am working on JT file. I have seen issue for native/program controlled route. Program Controlled should follow same procedure and should import body names as volume zones.

@ansutremel @waltersma @rajesh1359 @ashishagr25

**Comment by waltersma** [comment]
@Rohits28 Fixed in APS.
