### ISSUE TITLE
Alignment to other PyAnsys libraries

### ISSUE THREAD

**Issue by RobPasMue** [pyansys/pyprimemesh#304]
As per private conversation with @waltersma, I spend some time reviewing the repository and identified the following potential tasks. These will allow to align to other PyAnsys libraries:

- [x] #341
- [x] #340
- [x] #339
- [x] #338
- [x] #336
- [x] #337

I think those are the main major changes I can think of! I'd be happy to help as needed. Please let me know if you agree with all the changes. I'd create smaller PRs for each of the aforementioned tasks so that it is easier to review. And thanks in advance!

**Comment by ninad-kamat** [comment]
The changes needed for the next release have been synced up with our internal fork now. You can proceed with the refactoring necessary to complete the tasks above. Keep me in the loop with your PRs.

**Comment by RobPasMue** [comment]
Sure, thanks @ninad-kamat! Opening individual issues for each of the above points 😄

**Comment by RobPasMue** [comment]
Hi @ninad-kamat this has been finalized with the implementation of the multi-version docs. Right on time for your next 0.3.0 release =) Closing issue since it was only necessary for tracking purposes.
