### ISSUE TITLE
Undefined behaviour when file is not provided

### ISSUE THREAD

**Issue by AlejandroFernandezLuces** [pyansys/pyprimemesh#309]
# Bug
When initializing a model, it is required to have a file loaded to use it. However, you can initialize a model without loading the file, so some methods behaviour will be undefined. 

If the requirements for using the model are not met, it should raise an error to notify that it can't be used.

This issue arises from discussion in PR #291 

# Code to replicate the bug
```python
import ansys.meshing.prime as prime

# uses pytest to initialize the server
def test_sizecontrol(get_remote_client):
    model = get_remote_client.model

    size_control = prime.SizeControl(model, 0, 0, "foo")

    result = size_control.set_suggested_name('bar')
    assert result.assigned_name != '' # results in false
    assert result.assigned_name == size_control.name
```

**Comment by waltersma** [comment]
APS 776437
