### ISSUE TITLE
Correct link for PyAnsys in https://prime.docs.pyansys.com

### ISSUE THREAD

**Issue by prajaktmahajan** [pyansys/pyprimemesh#329]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

https://prime.docs.pyansys.com/ for this link    
PyAnsys  is linked to https://prime.docs.pyansys.com/pyansys
but it should link to https://docs.pyansys.com/ like other products 

### 📝 Steps to reproduce

open link https://prime.docs.pyansys.com/  and click on PyAnsys , it should go to https://docs.pyansys.com/

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.7

### 📦 Installed packages

```shell
NA
```

**Comment by RobPasMue** [comment]
I think this is working. There may have been an issue in the past with the breadcrumbs, but for me, whenever I click on "PyAnsys" it takes me to https://docs.pyansys.com/
