### ISSUE TITLE
Add a feature for checking available grpc ports while launching server

### ISSUE THREAD

**Issue by rajesh1359** [pyansys/pyprimemesh#349]
### 📝 Description of the feature

Add a check in the launch_prime() function to check if the port 50055 is blocked or not. If it is blocked then use available port and add a warning.

Similar check can be implemented even if the user specifies a port in the function.

**Comment by ninad-kamat** [comment]
@rajesh1359 This is already implemented in `launch_prime()`. The only difference in what you are saying and what is implemented is that if the given port is not available, the client will automatically pick the next available port in the sequence. So, for example, if port 50055 was not available, it will pick 50056. This only occurs if you are using the default IP address which is localhost. For any other IP address, we respect the port provided by the user and error out if that port is not available.

**Comment by rajesh1359** [comment]
Thanks @ninad-kamat . I checked the source code again and get_available_local_port seems to be finding the next available local port.
