### ISSUE TITLE
Please document the specific licenses that can be used to run Ansys Prime Server

### ISSUE THREAD

**Issue by landon-kanner** [pyansys/pyprimemesh#376]
### Description of the modifications

README.md states, "The use of Ansys Prime Server requires a legally licensed copy of Ansys Workbench."  There is no Workbench license.  What specific licenses can be used to run Ansys Prime Server?

**Comment by srpyprime** [comment]
Added the following in Readme and Getting started  documents

You must have Ansys 2023 R1 or newer versions installed for Ansys Prime Server (optionally, CAD readers can be configured). Ansys Prime Server requires a Preppost or CFD Preppost license to run.

**Comment by kmahajan-cadfem** [comment]
Is there any way to actually mention which license should the server use or to set any priority as which license will be used by the prime server.

many of the pyansys modules try to use the first available license, overall there should be a mechanism to choose the license, in some cases it is possible to send extra arguments to the server, but I did not find anything in case of Prime

**Comment by kmahajan-cadfem** [comment]
> Is there any way to actually mention which license should the server use or to set any priority as which license will be used by the prime server.
> 
> many of the pyansys modules try to use the first available license, overall there should be a mechanism to choose the license, in some cases it is possible to send extra arguments to the server, but I did not find anything in case of Prime

@waltersma, any thoughts on above if this is not available right now would it be possible to add it to the feature list.

Thanks
