### ISSUE TITLE
Bug located in ... Body label imports

### ISSUE THREAD

**Issue by Rohits28** [pyansys/pyprimemesh#389]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

I am facing issue for importing body labels from SpaceClaim. Face labels are importing correctly.

### 📝 Steps to reproduce

You can create a simple box and assign body label in SpaceClaim. After importing into pyprimemesh it fail to import body labels

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

23R1SP1

### 🐍 Which Python version are you using?

3.9

### 📦 Installed packages

```shell
ansys-api-meshing-prime==0.1.1
-e git+https://github.com/pyansys/pyprimemesh@a8b05bdfdfa8d5c976cd0b46afa611152bd6a705#egg=ansys_meshing_prime
appdirs==1.4.4
certifi==2022.12.7
charset-normalizer==3.0.1
contourpy==1.0.7
cycler==0.11.0
fonttools==4.38.0
grpcio==1.51.1
idna==3.4
imageio==2.25.0
kiwisolver==1.4.4
matplotlib==3.6.3
numpy==1.24.1
packaging==23.0
Pillow==9.4.0
pooch==1.6.0
protobuf==3.20.3
pyparsing==3.0.9
python-dateutil==2.8.2
pyvista==0.38.1
requests==2.28.2
scooby==0.7.1
six==1.16.0
urllib3==1.26.14
vtk==9.2.5
```

**Comment by hlee0122** [comment]
Hi @Rohits28 it's been added/fixed in the 0.4.0 dev build so I will not create a duplicate defect for this. Thanks
