### ISSUE TITLE
Bug located in ...Surface Mesh generation for Topofaces

### ISSUE THREAD

**Issue by agvarghe** [pyansys/pyprimemesh#407]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

While trying to generate surface mesh on topofaces , I am coming across the following issue

![image](https://user-images.githubusercontent.com/113696961/224612708-f915e1cd-b048-4d07-9079-093c59173464.png)

### 📝 Steps to reproduce

`from ansys.meshing import prime
from ansys.meshing.prime.graphics import Graphics
from ansys.meshing.prime import lucid

client=prime.launch_prime(timeout=15)
model=client.model

fileIO=prime.FileIO(model)
cad_params=prime.ImportCadParams(model,part_creation_type=prime.PartCreationType.BODY )
fileIO.import_cad(r"C:\Users\agvarghe\Downloads\Design1.scdoc",cad_params)
parts=model.parts
mesher=lucid.Mesh(model)
surfer=prime.Surfer(model)
compute_param=prime.ComputeVolumesParams(model, create_zones_type=prime.CreateVolumeZonesType.PERVOLUME, volume_naming_type=prime.VolumeNamingType.BYFACELABEL)
mesh=prime.AutoMesh(model=model)
automesh_params=prime.AutoMeshParams(model,volume_fill_type=prime.VolumeFillType.TET)
for part in parts:
    surfer_params=prime.SurferParams(model, min_size=1, max_size=8, growth_rate=1.2)
    print(part.id, part.get_topo_faces() )
    surfer.mesh_topo_faces(part.id, part.get_topo_faces(), surfer_params)
`

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

2023R1 , 

### 🐍 Which Python version are you using?

3.7

### 📦 Installed packages

```shell
-
```

**Comment by waltersma** [comment]
Hi @agvarghe, reported error is "invalid constant size".  Default sizefieldtype used in this instance is constant and requires the surfer_params.constant_size to be set.  If you require a variable size surface mesh you will need to compute a volumetric size field.  Does this resolve the issue you are seeing? Thanks
