### ISSUE TITLE
Volume named selections are not exported in cdb format using export_mapdl_cdb

### ISSUE THREAD

**Issue by tletutour-an** [pyansys/pyprimemesh#418]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

SpaceClaim named selections are usually exported as labels in pyprimemesh. When exporting to CDB file, those labels are converted to CM objects. This however does not work if the named selection is generated from a solid. This prevents from selecting different solids in the mesh, and thus to apply different material properties to solid entities. Any work-around to get solid-wise element/node lists would be appreciated. 
![image](https://user-images.githubusercontent.com/64088931/226919720-5bacd420-79d3-4740-ae9c-7ef155fed92b.png)
 below is output of print(model) in stdout after CAD import 
===========================
Part Name: dummy_geometry
Part ID: 2
    4 Topo Edges
    6 Topo Faces
    2 Topo Volumes

    0 Edge Zones
        Edge Zone Name(s) : []
    0 Face Zones
        Face Zone Name(s) : []
    2 Volume Zones
        Volume Zone Name(s) : [corps1, corps2]

    3 Label(s)
        Names: [face_ns, other_solid_ns, solid_ns]

    Bounding box (-11.1803 -11.1803 0)
                 (11.1803 11.1803 30)
=====================
Below is output of pymapdl output of cmlist command
 ** WARNING: PRE-RELEASE VERSION OF MAPDL 23.2BETA
  ANSYS,INC TESTING IS NOT COMPLETE - CHECK RESULTS CAREFULLY **

    NAME                            TYPE      SUBCOMPONENTS

  FACE_NS                           NODE

### 📝 Steps to reproduce

- make a simple geometry in SpaceClaim (23R2)
- In this geometry create two types of named selection : one of a face and one of a volume
- Save the geometry and mesh it using pyprimemesh
- Export it using the export_mapdl_cdb function
- Read it using MAPDL and run the command cmlist
- Only the surface named selection cm object will be shown

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

23R2 prerelease

### 🐍 Which Python version are you using?

3.8

### 📦 Installed packages

```shell
WARNING: Ignoring invalid distribution -nsys-fluent-core (c:\users\tletutou\pyscs-lib\venv\lib\site-packages)
aiohttp==3.8.3
aiosignal==1.3.1
ansys-api-fluent==0.3.5
ansys-api-mapdl==0.5.1
ansys-api-meshing-prime==0.1.1
ansys-api-platform-instancemanagement==1.0.0b3
ansys-corba==0.1.1
ansys-dpf-core==0.7.2
ansys-dpf-gate==0.3.0
ansys-dpf-gatebin==0.3.0
ansys-dpf-post==0.2.5
ansys-fluent-core==0.12.3
ansys-grantami-bomanalytics==1.0.1
ansys-grantami-bomanalytics-openapi==1.0.0
ansys-grpc-dpf==0.7.0
ansys-mapdl-core @ git+https://github.com/pyansys/pymapdl.git@d21760ab0976cb639c42ad1b7128b9aa3aabb61e
ansys-mapdl-reader==0.52.3
# Editable install with no version control (ansys-meshing-prime==0.4.0.dev4)
-e c:\users\tletutou\downloads\pyprimemesh-main
ansys-openapi-common==1.1.1
ansys-platform-instancemanagement==1.0.2
ansys-seascape==0.2.0
appdirs==1.4.4
async-timeout==4.0.2
attrs==22.1.0
cachetools==5.2.0
certifi==2022.9.24
cffi==1.15.1
charset-normalizer==2.1.1
click==8.1.3
clr-loader==0.2.4
colorama==0.4.6
commonmark==0.9.1
contourpy==1.0.6
cryptography==38.0.4
cycler==0.11.0
fonttools==4.38.0
frozenlist==1.3.3
geomdl==5.3.1
google-api-core==2.10.1
google-api-python-client==2.68.0
google-auth==2.14.1
google-auth-httplib2==0.1.0
googleapis-common-protos==1.56.4
grpcio==1.50.0
h5py==3.7.0
httplib2==0.21.0
idna==3.4
imageio==2.22.4
importlib-metadata==4.13.0
joblib==1.2.0
kiwisolver==1.4.4
matplotlib==3.6.2
meshio==5.3.4
multidict==6.0.2
networkx==3.0
NEURON==8.0
ntlm-auth==1.5.0
numpy==1.23.4
opencv-python==4.7.0.68
packaging==21.3
pandas==1.5.1
Pillow==9.3.0
plumbum==1.8.0
pooch==1.6.0
protobuf==3.20.1
protoc-gen-swagger==0.1.0
psutil==5.9.4
pyaedt==0.6.3
pyansys-tools-versioning==0.3.3
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
Pygments==2.14.0
pyiges==0.2.1
pyparsing==3.0.9
pypiwin32==223
python-dateutil==2.8.2
pythonnet==3.0.0rc6
pytwin==0.2.0
pytz==2022.6
pyvista==0.37.0
PyWavelets==1.4.1
pywin32==305
requests==2.28.1
requests-negotiate-sspi==0.5.2
requests-ntlm==1.1.0
rich==13.1.0
rpyc==5.0.1
rsa==4.9
scikit-image==0.19.3
scikit-learn==1.2.1
scipy==1.9.3
scooby==0.7.0
six==1.16.0
threadpoolctl==3.1.0
tifffile==2023.2.3
tqdm==4.64.1
typing_extensions==4.4.0
uritemplate==4.1.1
urllib3==1.26.12
vtk==9.2.2
wslink==1.9.1
yarl==1.8.1
zipp==3.10.0
```

**Comment by waltersma** [comment]
@tletutour-an  closing as looks to be duplicated with #419
