### ISSUE TITLE
Bug located in ...query function to check volumes / cell zonelets

### ISSUE THREAD

**Issue by agvarghe** [pyansys/pyprimemesh#424]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

For the attached scripts its observed that when i try to query for volumes associated with a part and the cell zonelets associated with the part, it returns 0 unless i delete topology . Screenshot from the terminal can be seen below 

1. Without delete topology

_0
Volume Zone Name :  box_1
Total number of cell zones, 0
Total cell count, 209
Total number of tet cells, 209
Total number of tri faces, 108
0
Volume Zone Name :  box_2
Total number of cell zones, 0
Total cell count, 199
Total number of tet cells, 199
Total number of tri faces, 108_

2. With delete topology

_1
Volume Zone Name :  box_1
Total number of cell zones, 1
Total cell count, 209
Total number of tet cells, 209
Total number of tri faces, 108
1
Volume Zone Name :  box_2
Total number of cell zones, 1
Total cell count, 199
Total number of tet cells, 199
Total number of tri faces, 108_

### 📝 Steps to reproduce

`
import os
import time
from ansys.meshing import prime
from ansys.meshing.prime.graphics import Graphics
from ansys.meshing.prime import lucid
#input Files
workindDirectory="E:\PyPrimeMesh\Scripts"
cadFileName="two_box.scdoc"
export_file = os.path.join(workindDirectory,'exported_cdb.cdb')

with prime.launch_prime(timeout= 30 ) as client:
    model=client.model
    meshUtil=lucid.Mesh(model)
    startTime=time.time()

    #CAD Import
    fileIO=prime.FileIO(model)
    fileIO.import_cad(os.path.join(workindDirectory,cadFileName),
                    params=prime.ImportCadParams(model=model,
                                                part_creation_type=prime.PartCreationType.BODY,
                                                cad_reader_route=prime.CadReaderRoute.PROGRAMCONTROLLED,
                                                length_unit=prime.LengthUnit.MM))
    stopTime=time.time()
    print(stopTime-startTime)
    
    #Draw Model
    display=Graphics(model)
    #display()

    #Generate Surface Mesh
    meshUtil.surface_mesh(min_size=0.5, max_size=4)
    #display()

    #Compute Regions
    for part in model.parts:
        part.compute_topo_volumes(params=prime.ComputeVolumesParams(model,
                                                                volume_naming_type=prime.VolumeNamingType.BYFACELABEL,
                                                                create_zones_type=prime.CreateVolumeZonesType.PERVOLUME))
        #part.delete_topo_entities(params=prime.DeleteTopoEntitiesParams(model,
        #                                                            delete_geom_zonelets=True))
        print(len(part.get_volumes()))
        for zone in part.get_volume_zones():
            print("Volume Zone Name : ", model.get_zone_name(zone))

        #Generate Volume
        meshUtil.volume_mesh(volume_fill_type=prime.VolumeFillType.TET)

        #Part Summary
        summary=part.get_summary(params=prime.PartSummaryParams(model))
        print("Total number of cell zones," , summary.n_cell_zonelets)
        print("Total cell count," , summary.n_cells)
        print("Total number of tet cells,", summary.n_tet_cells)
        print("Total number of tri faces,", summary.n_tri_faces)
    

`

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

2023 R1

### 🐍 Which Python version are you using?

3.8

### 📦 Installed packages

```shell
0
Volume Zone Name :  box_1
Total number of cell zones, 0
Total cell count, 209
Total number of tet cells, 209
Total number of tri faces, 108
0
Volume Zone Name :  box_2
Total number of cell zones, 0
Total cell count, 199
Total number of tet cells, 199
Total number of tri faces, 108
```

**Comment by hlee0122** [comment]
I would say it's an improvement on documentation to include part summary for both topoentities and zonelets.

**Comment by agvarghe** [comment]
Thanks for the confirmation Hao , This was a concept issue . I will mark the defect closed. 

Thanks
